### PR TITLE
Closed loop control

### PR DESCRIPTION
**Pull request by lirwin3007**
Implements required CAN messages for the 1HCL closed-loop control board

(To be merged alongside Duet3D/CANlib#3 & Duet3D/Duet3Expansion#4)

### CODE REVIEW

**Review by dc42 — CHANGES_REQUESTED** [review]
It looks like you have inadvertently reformatted GCodeBuffer.h. Please revert GCodeBuffer.h to the version from 3.4-dev.

**Review by dc42 — COMMENTED** [review]
Some methods in ClosedLoop.cpp are declared neither noexcept nor THROWS(GCODE_EXCEPTION). For example, OpenDataCollectionFile and CloseDataCollectionFile. Please fix. Also, if these functions are for use in that file only, please declare them 'static'.

**Comment by lirwin3007** [comment]
> It looks like you have inadvertently reformatted GCodeBuffer.h. Please revert GCodeBuffer.h to the version from 3.4-dev. 

:man_facepalming: that'll be VSCode working it's magic :upside_down_face: 
I'll revert that :+1:

**Comment by lirwin3007** [comment]
@dc42 all done :+1:

**Pull request merged**
