### PR TITLE
Support for 3-wire PT100 sensor

### PR DESCRIPTION
**Pull request by zlowred**
Hi dc42,

I'd like to propose optional support for 3-wire PT100 sensors.
Would be great if you could accept it.

Thanks

### CODE REVIEW

**Comment by zlowred** [comment]
Done, thanks for noticing I missed that

**Comment by parate** [comment]
Hi there,

sorry don't mean to spam this, but how would I connect a 3-wire sensor to the expansion board? I ordered mine from e3d, 2 red wires, one white.

Cheers, Florian

**Comment by zlowred** [comment]
I'm using custom expansion board I made myself. For the original one I'm afraid you'll have to modify  it which seem to be quite difficult (esp. given force2 pin of the chip is directly connected to the ground on their diagram); adapting generic one should be way easier.
Maybe Duet team would consider supporting 3-wire sensors in the next revision.

**Comment by dc42** [comment]
Is E3D really selling 3-wire PT100 sensors? I didn't find any on their web site.

**Comment by zlowred** [comment]
I can't say about E3D, but there are lots (most of I believe) of sensors that are sold as 2-wire but actually have two red wires connected together. This is the only reason I bothered with building custom expansion board and adding 3-wire sensor support.
2 wires less accurate, 4 wires really hard to find in the format that fits E3D heater block.

**Comment by zlowred** [comment]
I've got [this](https://www.aliexpress.com/item/3D-Ultimaker2-UM2-PT100-A-Sensor-Thermal-Resistance-Sensor-M3-15-1500mm-Hotend-Temperature-Senor-2wires/32810452036.html?spm=a2g0s.9042311.0.0.vMq5ui) one. If you looks at the picture you'll see two red wires connected to the same connector terminal. Most of what I was able to find (with 3mm diameter sensor 10-15mm long) look the same.

**Pull request merged**
