### PR TITLE
Stepper brake configure: M594

### PR DESCRIPTION
**Pull request by thehans**
Its been a while since I started trying to add this feature, but I think its in a good state to review.

Related: https://forum.duet3d.com/topic/7420/recommendation-for-accessing-enable-pins-for-stepper-brakes/6

### CODE REVIEW

**Comment by T3P3** [comment]
@thehans new features will not be added to RRF 2 so please resubmit this for RRF 3

Its worth discussing with David on the forum before submitting the request.

**Comment by thehans** [comment]
I did discuss on the forums before creating the PR, that's what the link goes to.  Anyways, it was ignored long enough that I no longer am working on the project or care about the feature, so whatever.

**Comment by dc42** [comment]
@thehans, would you care to produce a draft specification for how M594 should work in RRF3? It's important that the specification is one that can be implemented on expansion boards over CAN bus. If we can agree on that, either you can submit a PR for RRF3, or I can implement it.

**Comment by thehans** [comment]
As I said I no longer have any interest in the feature, so I don't intend to put any more effort into it.  
You may use my changes as a starting point for adapting to whatever latest branch, or re-implement it entirely, makes no difference to me.

**Comment by dc42** [comment]
Stepper brake configuration has been implemented in RRF 3.4. See https://docs.duet3d.com/en/User_manual/Reference/Gcodes#m5697-configure-motor-brake-port.

**Pull request closed without merging**
