### PR TITLE
Tighter Hangprinter Compatibility

### PR DESCRIPTION
**Pull request by tobbelobb**
I updated the Hangprinter kinematics using the equation derived here:
http://vitana.se/opr3d/tbear/2017.html#hangprinter_project_29

Best regards,

### CODE REVIEW

**Comment by tobbelobb** [comment]
The now enormous HangprinterKinematics::Configure method should probably be split up, so that FORMAT_STRING_LENGTH can come back down to 256.

One suggestion is to move 'R' (spoolRadii), 'G' (motorGearTeeth), 'H' (spoolGearTeeth), and 'J' (fullStepsPerRevolution) parameters to M92, as they could be used to calculate stepsPerMm on other types of kinematics as well.

**Comment by dc42** [comment]
Thanks for all your contributions. I am currently on holiday so I will review and action your contributions when I return.

**Comment by tobbelobb** [comment]
Hi David! Tony has notified me that you're away. I hope you have a wonderful holiday. My own starts on Monday.

When you're back, don't hesitate to throw things around if I've gone against code norms, principles, or best practices. I have relatively little experience with C++ and object oriented code.

Posting my todo here in case you get curious when I'm away and unavailable:
 - `G95` like here: [Marlin_main.cpp](https://github.com/tobbelobb/Marlin/blob/6628831e079720c8e3ea87e3e8d5711cc562b4c4/Marlin/Marlin_main.cpp#L6508). Maybe send "G95" in ascii, not 95 as hex (0x5f) as I've done in Marlin.
 - `G96` like here: [Marlin_main.cpp](https://github.com/tobbelobb/Marlin/blob/6628831e079720c8e3ea87e3e8d5711cc562b4c4/Marlin/Marlin_main.cpp#L6557).
 - `M114 S1` or a better solution for collecting encoder data.
 - Geometry sanity check on anchor location configuration like here: [SanityCheck.h](https://github.com/tobbelobb/Marlin/blob/6628831e079720c8e3ea87e3e8d5711cc562b4c4/Marlin/SanityCheck.h?utf8=%E2%9C%93#L708).
 - Milestone reached: Marlin feature parity.

The i2c usage in itself creates a wish-list
 - Adjustment of `M569`, so we can do
```
M584 A5 B6 C7 D8 ; This should already work
M569 P5 I0x0a  ; Configure driver 5 to be external, connected with i2c address 0x0a
M569 P6 I0x0b  ; Configure driver 6 to be external, connected with i2c address 0x0b
...
```
or maybe better
```
M569 PA I0x0a  ; Configure machine axis with the name A to be external, connected with i2c address 0x0a
...
```
Gcodes that should be forwarded to external drivers via i2c:
 - `M906` (set motor currents). Adjusts [Mechaduino `iMAX`](https://gitlab.com/tobben/mechaduino-code-for-auto-calibration/blob/697ac018c743d5d8d036287108161aab38ee777b/Mechaduino/Mechaduino/Parameters.cpp#L33).
 - `M350` (set microstepping). Adjusts [Mechaduino `stepangle`](https://gitlab.com/tobben/mechaduino-code-for-auto-calibration/blob/697ac018c743d5d8d036287108161aab38ee777b/Mechaduino/Mechaduino/Parameters.cpp#L27).
 - Also `M301` (Set PID parameters) should get a D-parameter, so Mechaduino PID tuning can be done with gcodes from Duet Web Control. It would look like:
```
M350 D5 P15.0 I0.2 D250.0 ; PID tune the motor connected to driver 5
```
The Mechaduino-side variables are called [`pKp`, `pKi`, `pKd`](https://gitlab.com/tobben/mechaduino-code-for-auto-calibration/blob/697ac018c743d5d8d036287108161aab38ee777b/Mechaduino/Mechaduino/Parameters.cpp#L9).
 - The Mechaduino code that handles received i2c: [Utils.cpp](https://gitlab.com/tobben/mechaduino-code-for-auto-calibration/blob/master/Mechaduino/Mechaduino/Utils.cpp#L42). There's also [giveAngle()](https://gitlab.com/tobben/mechaduino-code-for-auto-calibration/blob/master/Mechaduino/Mechaduino/Utils.cpp#L37) that is called upon i2c request. Used during `M114 S1`.
 - Test with motors and heaters attached. It will probably be August before I get here...

**Comment by tobbelobb** [comment]
G95 support check.

Mechaduino side of G95 (and G96) here: [Gitlab commit](https://gitlab.com/tobben/mechaduino-code-for-auto-calibration/commit/4d65090f6072950c95fd7704daedb1d38c3d43b1). I created a branch called [RepRapFirmware_compatibility](https://gitlab.com/tobben/mechaduino-code-for-auto-calibration/tree/RepRapFirmware_compatibility) to dev on until code is tested on hardware.

**Comment by tobbelobb** [comment]
G96 and M114 S1 also check but untested on hardware.

**Comment by tobbelobb** [comment]
The Hangprinter code (excluding the Mechaduino related code) has been tested and works. See Michael Delay's post here: https://www.facebook.com/groups/hangprinter/permalink/428191971024301/

**Comment by tobbelobb** [comment]
Hi @dc42 I'm working on how to move the Hangprinters individual axes (G1 S1 and G1 S2).

I've noticed that they always call `InverseTransform`, and that this triggers some problems:

The `sqrtf` here sometimes get negative arguments, so we need to guard it with a fabs: https://github.com/dc42/RepRapFirmware/blob/0930dc86a9f585eddbae29ac16e9399cd0aa367f/src/Movement/Kinematics/HangprinterKinematics.cpp#L321 I haven't yet backtracked if this still leaves the equations valid.

With default anchor positions, the values `Yab`, `Ybc`, `Yca`, `Zab`, `Zbc`, `Zca`, `P`, `P2`, `Q`, `R`, `U`, and `A` all become equal to zero. This leads to division by zero errors down again once `InverseTransform` is invoked.

Both of the above problems leads to `NaN`s being stored in `machinePos`. The `NaN`s causes the DuetWifi to reboot when they're sent to the web interface. Debugging through serial does not reboot the board.

Inserting the `fabs` guard and using different anchor position parameters lets me use `G1 S2`. However, since G1 S2 will mostly be used when lines are slack we'd prefer if `MotorStepsToCartesian` (which calls `InverseTransform`) is not called at all after individual motor moves. We'd rather leave all internal counters untouched after a nonzero movetype move.

Does RRF have a mechanism for storing and retrieving machine state, or should I go for trying to avoid touching counters by wrapping the lines where they are incremented? In Marlin I used `if (count_this_move)` statements, would this make sense in RRF as well?

I will get around these problems of you don't have the time to help me, but your input would be very valuable. Thanks.

**Comment by tobbelobb** [comment]
Hi @dc42 . I've done my first attempts at talking to the second ODrive via SERIAL_WIFI_DEVICE (the tx/rx on the EPS_COMMS header), but I'm not able to establish the connection.

So I read in the schematics and found a note: "J34 not populated in production boards".
Does this mean that I will never be able to use the UTXD1/URXD1 pins to control my second ODrive?

**Comment by vmario89** [comment]
hi, as this PR is really old but seems to contain a lot of essentials: will they ever be merged into official RepRapFirmware?

**Comment by dc42** [comment]
Unfortunately this PR takes over UART ports for use with Mechaduino, therefore I cannot include it in the standard release because of its impact on other users. If the parts that don't impact on other users are moved to a separate PR then I can consider including those parts in the standard release.

**Comment by tobbelobb** [comment]
Just for reference: This PR does not take over pins, and is not for use with Mechaduino.
It was implemented for use with ODrives.
It allows users to configure a pair of USART pins to act as UART if requested.
If not configured as UART, those pins will act as before, that is serve as SPI pins for thermocouple boards or any other use case they may have.
The gcode to configure this is:
```
; Connect ODrive 0 to Serial device 1 at 115200 baud
M569 Q0:1:115200
; Connect ODrive 1 to Serial device 99 at 115200 baud (This makes USART pins act as UART)
M569 Q1:99:115200
```
Copied from the config.g over at the Hangprinter repo:
https://gitlab.com/tobben/hangprinter/-/blob/af45cef15ec36ad5d5c91561514e49045c79ce9b/firmware/RepRapFirmware/Duet2/config.g

The Hangprinter repo also serves a pre-built binary for those who still use this code:
https://gitlab.com/tobben/hangprinter/-/blob/af45cef15ec36ad5d5c91561514e49045c79ce9b/firmware/RepRapFirmware/Duet2/Duet2CombinedFirmware.bin

Note that the binary linked above is unsupported, and will remain available only through the link in this comment.
Hangprinter went on to use CAN bus for communicating with ODrives, instead of UART.
That implementation is now merged, see https://github.com/Duet3D/RepRapFirmware/pull/531.

**Pull request closed without merging**
