### PR TITLE
[WIP] M309: add T parameter to specify the temperature increase(s) per …

### PR DESCRIPTION
**Pull request by timschneider**
- M309: added T parameter to specify the temperature increase(s) per unit of extrusion speed

The dynamic temperature increase allows the temperature to be increased as a function of the average extrusion speed in mm/sec. The implementation is analogue to that of Extrusion Feedforward. 
Example: Hotend 0 temperature of 220°C and an extrusion speed of 1 mm/sec with an M309 P0 T8 results in a temperature of 228°C.

See https://forum.duet3d.com/topic/36364/feature-adaptive-feedforward-temperature-setpoint for more infos.

### CODE REVIEW

**Comment by timschneider** [comment]
Changed title to WIP as it is not able to merge this PR into the main branch right now without breaking the compile chain for duet2 boards due to too less ROM.

**Comment by dc42** [comment]
@timschneider you may find there is sufficient free flash memory to add this to the 3.6 build even on Duet 2.

Please add the feedforward temperature coefficient to the object model too, assuming the heater feedforward coefficient is already in it.

**Comment by timschneider** [comment]
@dc42 thank you for pointing that out! I was testing it with the 3.5 branch for the Duet2. 
I've added the `temperatureFeedForward` to the Object Model and initialized the temperatureFeedForward to 0.0 in `Tool::Create`.

**Comment by timschneider** [comment]
I'll let it stay at WIP as long as extrusion feedforward is broken in v3.6. See https://forum.duet3d.com/topic/36738/3-6-0-beta-1-heater-feedforward-not-working.
It apperas that `void Tool::ApplyFeedForward(float extrusionSpeed) const noexcept` is never called with the new Input Shaping.

**Comment by dc42** [comment]
Thanks Tim, please keep it as WIP until I have fixed heater feedforward, which I hope will be in time for 3.6beta2.

**Comment by timschneider** [comment]
Thanks a lot David for integrating this feature!

https://github.com/Duet3D/RepRapFirmware/commit/b300085b44b2fe403d231a674b3b29f702c6b66f

We can close this PR

**Pull request closed without merging**
