### PR TITLE
Build Portability Updates

### PR DESCRIPTION
**Pull request by gtjoseph**
These updates should make it easier for developers on different
platforms to contribute.

* Remove the definition of GccPath from the project definition.
* Replace references to GccPath with GccPath_Arm_7_2018_q2.
* Update Build instructions to indicate that GccPath_Arm_7_2018_q2
  must be set in the workspace C/C++ Build Variables.
* Remove .settings/language.settings.xml from the git index.
* Update .gitignore to add .settings/language.settings.xml
  and the build variant output directories.

### CODE REVIEW

**Comment by gtjoseph** [comment]
i just rebased this from "dev" with no issues.

**Comment by chrishamm** [comment]
In principle I think this is a good idea - I didn't know workspace variables could be globally defined (in Window -> Preferences -> C/C++ -> Build -> Build Variables). But may I propose to rename these variables to "ArmGccPath" and "XtensaGccPath"? That would make future toolchain updates easier.

**Comment by chrishamm** [comment]
PS: The build variables EspBootFile and EspToolPath of th DWSS project could be moved to the workspace settings too.

**Comment by gtjoseph** [comment]
> In principle I think this is a good idea - I didn't know workspace variables could be globally defined (in Window -> Preferences -> C/C++ -> Build -> Build Variables). But may I propose to rename these variables to "ArmGccPath" and "XtensaGccPath"? That would make future toolchain updates easier.

Works for me.
@dc42 ?

**Pull request merged**
