### PR TITLE
ExceptionsHandlers: added missing include

### PR DESCRIPTION
**Pull request by mfs12**
Hey @dc42 , i think an include is missing, not sure about the other branches. So perhaps it needs to merged as well to some more.

### CODE REVIEW

**Comment by dc42** [comment]
stdexcept does not need to be included when using the tools recommended in the build instructions. I suspect you are using a different compiler version or different library. What error message do you get when you don't include stdexcept?

**Comment by mfs12** [comment]
Ok, i wasn't aware of that.

I am using stock versions of Arch Linux:
- arm-none-eabi-newlib 4.1.0
- arm-none-eabi-gcc 11.1.0

The reported error message is:

```sh
../src/Hardware/ExceptionHandlers.cpp:284:14: error: 'terminate_handler' in namespace 'std' does not name a type
  284 |         std::terminate_handler __terminate_handler = Terminate;
```

**Comment by mfs12** [comment]
@dc42 but then some other header is likely to implicitly include this header. Where is this type defined in your toolchain?

**Comment by mfs12** [comment]
@dc42 i switched to the recommended toolchain. And then no error or warning is reported. I also changed the patch to use exception-include instead of stdexcept which would be handy to stay compatible to other toolchains as well.

**Comment by dc42** [comment]
RRR now compiles using more recent versions of GCC.

**Pull request closed without merging**
