### PR TITLE
Added support for custom MAX31865 reference resistors

### PR DESCRIPTION
**Pull request by bpaczkowski**
The reference resistor value defaults to 400, can be changed with the R parameter of the M305 GCode.

### CODE REVIEW

**Comment by bpaczkowski** [comment]
Summoning @dc42, any chance we could merge this for 1.20 release?

**Comment by dc42** [comment]
A few questions on your pull request:

- What is the source of the resistance table?
- The table just lists resistance values. I don't see any definition of what the steps in the table are.
- The code that replaces the interpolation looks unnecessarily complicated to me. Why are you not interpolating between the nearest two values in the table?

**Comment by bpaczkowski** [comment]
* The source of this table as mentioned in the comment are DIN 43760 and IEC 751 documents. Most likely merged together. The source of the table in it's current form is from this example adafruit project: https://github.com/adafruit/pt100rtd/blob/master/pt100rtd.h#L38
* The table index to temperature ratio is 1:1, as in the ohm difference between table value 0 and 1 corresponds to a temperature difference of 1 degree.
* You are correct about that one, I simplified this code just now.

**Comment by dc42** [comment]
Thanks, I'll review the changes as they stand now.

**Comment by dc42** [comment]
Three more changes please:

1. The use of >2K memory to hold the R-T table is excessive, given that the relationship is almost linear. I suggest you keep just the first column in each row (i.e. 10C intervals) and interpolate within each 10C interval. I have checked that this is accurate.

2. The new code to check for the R parameter should be before the previous conditional and set 'seen' to true, so that if the R parameter is given then it does not display the existing values.

3. When in display-only mode (because 'seen' has not been set), the value of the reference resistor should be included in the information displayed.

**Comment by bpaczkowski** [comment]
@dc42 Done. Also, if you're concerned about the size, we could remove some of the upper and lower ohm values. As it is now, the table specifies ohm values between -200 and 850 degrees, I doubt such low/high temperatures are needed for our use.

**Comment by dc42** [comment]
Thanks for making those changes. The size is a lot better now, but I'll probably increase the lower temperature limit to about -40C. I'll leave the upper temperature as 850C because we have customers who run at up to 1600C using thermocouples.

**Pull request merged**
