### PR TITLE
Add standby temp to JSON bed temps

### PR DESCRIPTION
**Pull request by gtjoseph**
https://forum.duet3d.com/topic/8708/report-bed-standby-temp-in-m408-json-responses

### CODE REVIEW

**Comment by dc42** [comment]
Please do not submit PRs that combine totally different changes.

I can accept the change to add bed standby temperature to the M408 response.

I can accept the change to remove language settings.xml

I cannot accept the change to move GccPath without further thought and modification, because it presupposes that all projects in the workspace, all branches of the repository and all configurations of the projects use the same value of GccPath, which is most certainly not the case.

**Comment by gtjoseph** [comment]
Sorry.  Github automatically combines commits into the same pull request which I hate.  I'll close this pull request and try and submit separate ones.

**Comment by gtjoseph** [comment]
Oh, how about a separate GccPath at the workspace level for each toolchain?

**Comment by gtjoseph** [comment]
Another alternative is to rename .cproject -> .cproject.official with the standard options, then add .cproject to .gitignore.   When you clone the project for the first time, you manually copy .cproject.template to .cproject and customize it the way you need.  Since it's in .gitignore, your changes stay local.

**Comment by dc42** [comment]
I think a separate workspace variable for each tool chain and version of that tool chain would work. For example, Gcc_Arm_7_2018_q2.

**Pull request closed without merging**
