### PR TITLE
Add M470 for mkdir and M471 for move

### PR DESCRIPTION
**Pull request by wilriker**
As discussed in https://forum.duet3d.com/topic/8858/command-to-move-rename-files.

### CODE REVIEW

**Comment by dc42** [comment]
Thanks for updating the GCodes wiki page at reprap.org. The character font of the "Rename or move a file or directory" text and the following entry (M500) is wrong. Please correct it. Also, please add a note that renaming across directories is supported (and test it, if you haven't already) but renaming across SD cards is not (and test what happens if you try).

**Comment by wilriker** [comment]
I don't have a secondary SD card so I cannot try it, unfortunately. Changed the formatting issue and amended the note about renaming across directories.

**Comment by wilriker** [comment]
Any update on merging this one?

**Comment by dc42** [comment]
This is on my list to do, should be soon.

**Comment by wilriker** [comment]
Cool, thanks!

**Comment by wilriker** [comment]
P.S.: I will add this to Duet GCode wiki now.

**Pull request merged**
