### PR TITLE
fix extrusion special move

### LINKED ISSUE #847: G1 H1 E moves not working in 3.5.0-beta.3
### Duet Forum Discussion Thread

https://forum.duet3d.com/topic/32153/m915-feature-is-loss-after-3-5-0-beta2-version-on-extruder

G1 H1 E moves no longer work.

### PR DESCRIPTION
**Pull request by alexjx**
I'm using the stall detection for loading filament. However, after upgrading to 3.5, this feature is broken. 

This patch tries to fix the extrusion special move, by making the extrusion check aware the check endstop flag.

BTW: I could not post anything to the forum since my account always got flags as SPAM...

### CODE REVIEW

**Comment by dc42** [comment]
@alexjx thanks for diagnosing this problem. I have gone back to the RRF 3.4 source code to determine which change to 3.5 broke this functionality. The change concerned was that in RRF 3.4 the check on whether the extruder movement is allowed is made in DDA::Start, which calls RepRap::GetProhibitedExtruderMovements, which uses currentTool to determine which tool to check. In RRF 3.5 the check is moved to DDA::Prepare, which uses the tool stored in the DDA to do the check. This tool is nullptr for a G1 H1 move.

Your change works by passing checkEndstops to Tool::ExtruderMovementAllowed and skipping the check if the tool is null and checkEndstops is set. A consequence of this is that the behaviour is changed: a G1 H1 E move will be permitted regardless of the hot end temperature, whereas in RRF 3.4 the hot end temperature will be checked unless cold extrusion is allowed.

I am considering whether this behaviour change is acceptable, bearing in mind that we have requests to support extruder endstop types other than stall in future. However, if we do accept it, then I think your changes can be simplified by changing DDA::Prepare to call Tool::ExtruderMovementAllowed only if checkEndstops is not set. Then it is not necessary to modify Tool::ExtruderMovementAllowed. If you agree, please make this change to your PR and include a comment explaining that we can't call Tool::ExtruderMovementAllowed at that point if checkEndstops is set because 'tool' will be null in that case.

See also forum thread https://forum.duet3d.com/topic/32153/m915-feature-is-loss-after-3-5-0-beta2-version-on-extruder and issue https://github.com/Duet3D/RepRapFirmware/issues/847.

To post on the forum, try creating a thread that does not contain any links. We can upvote your post, after which links should not cause a problem with the spam filter.

**Comment by alexjx** [comment]
@dc42 Thank you for reviewing the change. I think you are right, even for special move, we should have somewhat check for cold extrustion, therefore, my intension is to checkEndstop after the cold extrusion validation. But in order to do that I have to pass the checkEndstop as a parameter. This does seem to be a bit contaminating. 

Another possible solution is we let Tool::ExtruderMovementAllowed check return "state" instead of bool, so DDA could tell the situation it is in. 

What do you think?

**Comment by dc42** [comment]
@alexjx please make the change I requested (have the DDA call the check function only if checkEndstops is not set, and don;t pass checkEndstops to the check function). That will suffice for now. If we want to check for cold extrusion during special moves, I can add that check when the move is created.

**Comment by alexjx** [comment]
@dc42 please help reviewing the updated.

**Comment by dc42** [comment]
I don't think that's going to work. I think you need just this simple change: change the condition to:

`if (flags.checkEndstops || Tool::ExtruderMovementAllowed(tool, directionVector[drive] > 0, extruder))`

and of course change the comment before that line to explain why we are testing flags.checkEndstops. I'd do the change myself, but that way you wouldn't get the credit for it in the commit history.

**Comment by alexjx** [comment]
It's ok. I'm not trying to get any credit for this. Honestly I've got a working version for myself already. My goal is to raise the issue an see if I could do something to help. Thanks for pointing it out that the patch is not right. It sees my patch is cosuming more time than necessary. Please make the change and i will close this PR.

**Comment by dc42** [comment]
OK, thanks again for pinning down the problem.

**Pull request closed without merging**
